name: generate snake

on:
  push:
    branches:
    - master
    
  schedule:
    - cron: "0 0 * * *"
    
  

jobs:
  Generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Merge output -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: output
          target_branch: master
          github_token: ${{ github.token }}
          
      - name: Delete output branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: output
