name: Daily-snake-generation

on:
  push:
    branches:
    - master
    
  schedule:
    - cron: "0 0 * * *"
     

jobs:
  Generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Get datetime
        id: date
        run: |
          echo "::set-output name=date::$(date )"
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Snake updated at ${{ steps.date.outputs.date }}"
      
